fix(strophejs): provide disconnection timout
strophe/strophejs pull request #381
Opened 2021-11-30 20:06 UTC by DenisIrkhin

Motivation:
it's better to provide a manageable disconnection timeout to customers instead of having a hardcoded one.

@example:
in some cases we have race conditions when we call disconnect(it has 3000ms timeout) and start reconnection. The reconnection is succeded in 1sec and then we have doDisconnect called.

2021-11-30 20:10 UTC, DenisIrkhin commented
@jcbrand could we please have a realise with update You've done f61dbe53b2c64fa49cc915c33c9307cf4f756597
our CI complains about a security issues in `xmldom` old version.
Thank You in advance

2021-12-02 10:19 UTC, jcbrand requested changes
Thanks @DenisIrkhin 

Please see my two review comments

2021-12-02 10:22 UTC, jcbrand commented
@DenisIrkhin Concerning xmldom, the latest version is 0.7.5. You could make another MR that bumps the version to that and check whether it fixes your CI warning. I'd be happy to merge it.

2021-12-02 16:47 UTC, DenisIrkhin commented
@jcbrand Thank You Much for the fast reaction and review!

xmldom PR is 
https://github.com/strophe/strophejs/pull/384

Could You please review https://github.com/strophe/strophejs/pull/383
So we could have next release with all latest commits.
Thanks!

2021-12-03 08:01 UTC, merged

2021-12-03 08:01 UTC, jcbrand commented
Thanks!